mysql:
  container_name: mysql
  image: mysql/mysql-server:8.0
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  env_file:
    - .env
  environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_USER=${MYSQL_USERNAME}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DBNAME}
  ports:
    - "${MYSQL_PORT}:3306"
  volumes:
    - data:/var/lib/mysql